version: "3.8"
services:
  git:
    build:
      context: .
      target: built-git
    image: kindtek/safedb-repo
    entrypoint: tail -f /dev/null
    labels:
      com.docker.devenvironments: "true"
      com.docker.devenvironments.compose: "true"
      com.docker.devenvironments.container: "true"
      com.docker.devenvironments.name: sdb
  sdb:
    environment:
      - PATH=/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/sdb/solana/sdk/docker-solana/usr/bin
    ulimits:
      nofile:
        soft: 1000000
        hard: 1000000
    image: kindtek/safedb
    # working_dir: /sdb
    build:
      context: .
      target: built-sdb
    init: true
    entrypoint: tail -f /dev/null
    stop_signal: SIGKILL
    volumes:
      - sol-vol-sdb:/sdb/solana
      - yub-vol-sdb:/sdb/yubico-net-sdk
    labels:
      com.docker.devenvironments: "true"
      com.docker.devenvironments.compose: "true"
      com.docker.devenvironments.container: "true"
      com.docker.devenvironments.name: sdb

  sol:
    environment:
      - PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/sdb/solana/sdk/ubuntu-solana/usr/bin
    ulimits:
      nofile:
        soft: 1000000
        hard: 1000000
    image: kindtek/solana-safedb-alpine
    build:
      context: .
      target: built-sol
    init: true
    entrypoint: # tail -f /dev/null
    - "/bin/bash solana-run.sh"
    stop_signal: SIGKILL
    tty: true
    stdin_open: true
    volumes:
      - sol-vol-sdb:/sdb/solana
    ports:
      - "8899:8899"
    labels:
      com.docker.devenvironments: "true"
      com.docker.devenvironments.compose: "true"
      com.docker.devenvironments.container: "true"
      com.docker.devenvironments.name: sdb
  yub:
    environment:
      - PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
    image: kindtek/yubico-safedb-alpine
    # working_dir: /sdb/yubico-net-sdk/Yubico.NativeShims
    build:
      context: .
      # dockerfile: sdb/yubico-net-sdk/Yubico.NativeShims/docker/Ubuntu/Dockerfile
      target: built-yub
    init: true
    entrypoint: tail -f /dev/null
    stop_signal: SIGKILL
    volumes:
      - yub-vol-sdb:/sdb/yubico-net-sdk
    labels:
      com.docker.devenvironments: "true"
      com.docker.devenvironments.compose: "true"
      com.docker.devenvironments.container: "true"
      com.docker.devenvironments.name: sdb
networks:
  default:
    name: net
    attachable: true

volumes:
  sol-vol-sdb:
    name: yub-vol-sdb
    external: false
  yub-vol-sdb:
    name: yub-vol-sdb
    external: false
