version: "3.8"
services:
  # builder-sdb_dev:
  #   build:
  #     context: .
  #     cache_from:
  #       - sdb:builder-sdb_dev
  #     target: builder-sdb_dev
  #   image: sdb:builder-sdb_dev
  git:
    build:
      context: .
      target: clone-git-sdb_dev
    image: kindtek/sdb_dev-git
    entrypoint: tail -f /dev/null
    labels:
      com.docker.devenvironments: "true"
      com.docker.devenvironments.compose: "true"
      com.docker.devenvironments.container: "true"
      com.docker.devenvironments.name: sdb_dev
    volumes:
      - volume-sdb:/sdb
      - /var/run/docker.sock:/var/run/docker.sock

  sdb:
    # pull_policy:
    #   "always"
    environment:
      - PATH=/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/sdb/solana/sdk/ubuntu-solana/usr/bin
      #:/sdb/solana/sdk/docker-solana/usr/bin
    ulimits:
      nofile:
        soft: 1000000
        hard: 1000000
    image: kindtek/sdb_dev-sdb
    # working_dir: /sdb
    build:
      context: .
      target: built-sdb_dev
      # cache_from:
      #   - sdb:builder-sdb_dev
      #   - sdb:kindtek/sdb-sdb_dev
    init: true
    entrypoint: tail -f /dev/null
    stop_signal: SIGKILL
    # volumes:
    # - volume-sdb:/sdb
    # - /var/run/docker.sock:/var/run/docker.sock

    labels:
      com.docker.devenvironments: "true"
      com.docker.devenvironments.compose: "true"
      com.docker.devenvironments.container: "true"
      com.docker.devenvironments.name: sdb_dev
  sol:
    # pull_policy:
    #   "always"
    # depends_on:
    #   - "sdb"
    environment:
      - PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/sdb/solana/sdk/ubuntu-solana/usr/bin
    ulimits:
      nofile:
        soft: 1000000
        hard: 1000000
    image: kindtek/sdb_dev-sol
    build:
      context: .
      # dockerfile: sdb/solana/sdk/docker-solana/Dockerfile
      target: built-sol-sdb_dev
    init: true
    entrypoint:
      - "/bin/bash solana-run.sh"
    stop_signal: SIGKILL
    tty: true
    stdin_open: true
    volumes:
      - volume-sdb:/sdb
      # - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "8899:8899"
      # - ./sdb/solana/sdk/docker-solana/usr/bin:/usr/share/sol/bin
      # - ./sdb/yubico-net-sdk/Yubico.NativeShims/ubuntu-x64:/var/run/docker.sock
    labels:
      com.docker.devenvironments: "true"
      com.docker.devenvironments.compose: "true"
      com.docker.devenvironments.container: "true"
      com.docker.devenvironments.name: sdb_dev
  yub:
    # pull_policy:
    #   "always"
    depends_on:
      - "sdb"
    environment:
      - PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
    image: kindtek/sdb_dev-yub
    # working_dir: /sdb/yubico-net-sdk/Yubico.NativeShims
    build:
      context: .
      # dockerfile: sdb/yubico-net-sdk/Yubico.NativeShims/docker/Ubuntu/Dockerfile
      target: built-yub-sdb_dev
    init: true
    entrypoint: tail -f /dev/null
    stop_signal: SIGKILL
    # volumes:
    # - volume-sdb:/sdb
    # - /var/run/docker.sock:/var/run/docker.sock
    labels:
      com.docker.devenvironments: "true"
      com.docker.devenvironments.compose: "true"
      com.docker.devenvironments.container: "true"
      com.docker.devenvironments.name: sdb_dev
networks:
  default:
    name: networks-sdb_dev
    attachable: true
  # portainer_agent:
  #   driver: overlay
  #   attachable: true

volumes:
  volume-sdb:
    name: volume-sdb
    external: false
  # volume-sol:
  #   name: volume-sol
  #   external: false
  # volume-yub:
  #   name: volume-yub
  #   external: false
