#!/usr/bin/env bash
set -ex

cd "$(dirname "$0")"/../..
eval "$(/sdb/solana/ci/channel-info.sh)"
source sdb/solana/ci/rust-version.sh

CHANNEL_OR_TAG=
if [[ -n "$CI_TAG" ]]; then
  SOLANA_CHANNEL_OR_TAG=$CI_TAG
else
  SOLANA_CHANNEL_OR_TAG=$CHANNEL
fi

exit 0