#!/bin/bash
cd solana
CHANNEL=kindtek/solana-firewalled-alpine:latest CI=true /bin/bash sdk/docker-solana/build.sh
docker kindtek/solana-firewalled-alpine:latest tag kindtek/solana-firewalled-alpine:sdb-0.0.1 
docker push kindtek/solana-firewalled-alpine:latest