#!/bin/bash

cd yubico-net-sdk/Yubico.NativeShims
USER_ID=1000 GROUP_ID=1000 ARTIFACT_DIR=ubuntu-x64 /bin/bash build-ubuntu.sh

docker build push kindtek/yubico-safedb-ubuntu:sdb-y1.5.0.s0-A.1-u18.04
docker build tag kindtek/yubico-safedb-ubuntu:sdb-y1.5.0.s0-A.1-u18.04 docker build push kindtek/yubico-safedb-ubuntu:latest