version: "3.8"
services:


  yub:
    command:
      - infinity
    entrypoint:
      - sleep
    image: mono:latest
    build: docker build yubico-net-sdk/Yubico.NativeShims/Docker
    init: true
    labels:
      com.docker.devenvironments: "true"
      com.docker.devenvironments.compose: "true"
      com.docker.devenvironments.container: "true"
      com.docker.devenvironments.name: sdb_dev
    networks:
      default: null
    stop_signal: SIGKILL
    volumes:
      - type: volume
        source: volume-yub-bin
        target: /usr/bin
        
  sol:
    # command:
    #   - "apt-get update -qq && apt-get install -yq wget"
    # entrypoint:
    #   - "/usr/bin/solana-run.sh"
    build: docker build solana/api/docker-solana
    ports:
      - "8899:8899"
    init: true
    labels:
      com.docker.devenvironments: "true"
      com.docker.devenvironments.compose: "true"
      com.docker.devenvironments.container: "true"
      com.docker.devenvironments.name: sdb_dev
    networks:
      default: null
    stop_signal: SIGKILL
    volumes:
      - type: volume
        source: volume-sol-bin
        target: /usr/bin

  app:
    depends_on:
      - "sol"
      - "yub"
    #    - "agent"
    command:
      - infinity
    entrypoint:
      - sleep
    image: debian:bullseye
    init: true
    labels:
      com.docker.devenvironments: "true"
      com.docker.devenvironments.compose: "true"
      com.docker.devenvironments.container: "true"
      com.docker.devenvironments.name: sdb_dev
    networks:
      default: null
    stop_signal: SIGKILL
    volumes:
      - type: volume
        source: volume-yubi-bin
        target: /yub/bin
      - type: volume
        source: volume-sol-bin
        target: /sol/bin

  # agent:
  #   image: portainer/agent
  #   environment:
  #     AGENT_CLUSTER_ADDR: tasks.agent
  #     CAP_HOST_MANAGEMENT: 1
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock
  #     - /var/lib/docker/volumes:/var/lib/docker/volumes
  #     - /:/host
  #   ports:
  #     - target: 9001
  #       published: 9001
  #       protocol: tcp
  #       mode: host
  #   networks:
  #     - portainer_agent
  #   deploy:
  #     mode: global
  #     placement:
  #       constraints: [node.platform.os == linux]
networks:
  default:
    name: networks-sdb_dev
    attachable: true
  # portainer_agent:
  #   driver: overlay
  #   attachable: true

volumes:
  volume-yub-bin:
    name: volume-yubi-bin
  volume-sol-bin:
    name: volume-sol-bin
