version: "3.8"
# # name: yubico-net-sdk-distracted_rubin
x-var: &KINDTEK_SDB_REPO_URL_BRANCH >
  https://github.com/kindtek/yubico-net-sdk.git#sdb_dev#sdb_dev
services:
  agent:
    image: portainer/agent
    environment:
      AGENT_CLUSTER_ADDR: tasks.agent
      CAP_HOST_MANAGEMENT: 1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
      - /:/host
    ports:
      - target: 9001
        published: 9001
        protocol: tcp
        mode: host
    networks:
      - portainer_agent
    deploy:
      mode: global
      placement:
        constraints: [ node.platform.os == linux ]
  yubi:
    entrypoint: 
    - |
      git -C . clone https://github.com/kindtek/yubico-sdk-net.git 
      /bin/bash Yubico.NativeShims/build-ubuntu.sh
    image: docker/dev-environments-default:stable-1
    build:
      #context: https://github.com/kindtek/yubico-net-sdk.git#main # use develop branch since we are in main
      context: *KINDTEK_SDB_REPO_URL_BRANCH # use sdb_dev branch since we are in sdb#dev
      dockerfile: Yubico.NativeShims/docker/Ubuntu/Dockerfile
    init: true
    environment:
      - PATH=${PATH}
      - USERID=${USER_ID}
      - GROUPID=${GROUP_ID}
    labels:
      com.docker.devenvironments: "true"
      com.docker.devenvironments.compose: "true"
      com.docker.devenvironments.container: "true"
      com.docker.devenvironments.name: yubico-net-sdk-distracted_rubin
    networks:
      default: null
    stop_signal: SIGKILL
    volumes:
      - type: volume
        source: volume-yubico-net-sdk-distracted_rubin-sol
        target: /usr/bin
      - type: volume
        source: volume-docker-sock
        target: /var/run/docker.sock
      - type: volume
        source: volume-yubico-net-sdk-distracted_rubin
        target: /com.docker.devenvironments.code
      - type: volume
        source: vsCodeServerVolume-yubico-net-sdk-distracted_rubin-app
        target: /home/vscode
  sol:
    entrypoint:
    - |
      apt-get update -qq && apt-get install -yq wget 
      git -C . clone https://github.com/kindtek/solana.git 
      /bin/bash /sdk/docker-solana/build.sh 
      /usr/bin/solana-run.sh
    build:
      context: https://github.com/kindtek/solana.git
      #dockerfile: https://github.com/kindtek/yubico-net-sdk.git#develop:Yubico.NativeShims/docker/Ubuntu/Dockerfile
      dockerfile: /ci/docker-rust/Dockerfile
    image: docker/dev-environments-default:stable-1
    ports:
      - "8899:8899"
    init: true
    labels:
      com.docker.devenvironments: "true"
      com.docker.devenvironments.compose: "true"
      com.docker.devenvironments.container: "true"
      com.docker.devenvironments.name: yubico-net-sdk-distracted_rubin
    networks:
      default: null
    stop_signal: SIGKILL
    volumes:
      - type: volume
        source: volume-yubico-net-sdk-distracted_rubin-sol
        target: /usr/bin
      - type: volume
        source: volume-docker-sock
        target: /var/run/docker.sock
      - type: volume
        source: volume-yubico-net-sdk-distracted_rubin
        target: /solana
      - type: volume
        source: vsCodeServerVolume-yubico-net-sdk-distracted_rubin-app
        target: /home/vscode
  web:
    entrypoint:
      - sleep
      - infinity
      #image: docker/dev-environments-default:stable-1
    build: .
    ports:
      - "8080:8080"
    init: true
    environment:
      - PATH=${PATH}
      - USERID=${USER_ID}
      - GROUPID=${GROUP_ID}
    volumes:
      - type: volume
        source: volume-docker-sock
        target: /var/run/docker.sock
      - type: volume
        source: volume-yubico-net-sdk-distracted_rubin
        target: /app
    depends_on:
      - yubi
  app:
    depends_on:
      - sol
      - yubi
      - agent
    command:
      - infinity
    entrypoint:
      - sleep
    image: docker/dev-environments-default:stable-1
    init: true
    labels:
      com.docker.devenvironments: "true"
      com.docker.devenvironments.compose: "true"
      com.docker.devenvironments.container: "true"
      com.docker.devenvironments.name: yubico-net-sdk-distracted_rubin
    networks:
      default: null
    stop_signal: SIGKILL
    volumes:
      - type: volume
        source: volume-yubico-net-sdk-distracted_rubin-sol
        target: /usr/bin
      - type: volume
        source: volume-docker-sock
        target: /var/run/docker.sock
      - type: volume
        source: volume-yubico-net-sdk-distracted_rubin
        target: /com.docker.devenvironments.code
      - type: volume
        source: vsCodeServerVolume-yubico-net-sdk-distracted_rubin-app
        target: /home/vscode
networks:
  default:
    name: yubico-net-sdk-distracted_rubin_default-net-5
    attachable: true
  portainer_agent:
    driver: overlay
    attachable: true

volumes:
  volume-yubico-net-sdk-distracted_rubin:
    name: volume-yubico-net-sdk-distracted_rubin
    #external: true
  vsCodeServerVolume-yubico-net-sdk-distracted_rubin-app:
    name: vsCodeServerVolume-yubico-net-sdk-distracted_rubin-app
    #external: true
  volume-yubico-net-sdk-distracted_rubin-sol:
    name: volume-yubico-net-sdk-distracted_rubin-sol
    #external: true
  volume-docker-sock:
    name: volume-docker-sock
    #external: true
