version: "3.8"
services:
  sdb:
    # pull_policy:
    #   "always"
    environment:
      - PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/usr/sol/bin
    ulimits:
      nofile:
        soft: 1000000
        hard: 1000000
    image: kindtek/sdb_dev-sdb
    build:
      context: .
      target: installed-sdb_dev
    init: true
    stop_signal: SIGKILL
    volumes:
      - volume-bin-sol:/usr/sol/bin

networks:
  default:
    name: networks-sdb_dev
    attachable: true
  # portainer_agent:
  #   driver: overlay
  #   attachable: true

volumes:
  volume-bin-sol:
    name: volume-bin-sol
