version: "3.8"
services:
  sdb:
    # pull_policy:
    #   "always"
    environment:
      - PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/usr/sol/bin
    ulimits:
      nofile:
        soft: 1000000
        hard: 1000000
    image: kindtek/sdb_dev-sdb
    build:
      context: .
      target: installed-sdb_dev
    init: true
    stop_signal: SIGKILL
    volumes:
      - volume-bin-sol:/usr/sol/bin
  sol:
    # pull_policy:
    #   "always"
    environment:
      - PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/build/solana/sdk/docker-solana/usr/bin
    ulimits:
      nofile:
        soft: 1000000
        hard: 1000000
    image: kindtek/sdb_dev-sol
    build: ./solana
    init: true
    stop_signal: SIGKILL
    volumes:
      - volume-bin-sol:/build/solana/sdk/docker-solana/usr/bin
      # - ./build/solana/sdk/docker-solana/usr/bin:/usr/share/sol/bin
      # - ./build/yubico-net-sdk/Yubico.NativeShims/ubuntu-x64:/var/run/docker.sock
    labels:
      com.docker.devenvironments: "true"
      com.docker.devenvironments.compose: "true"
      com.docker.devenvironments.container: "true"
      com.docker.devenvironments.name: sdb_dev
  yub:
    # pull_policy:
    #   "always"
    environment:
      - PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin
    image: kindtek/sdb_dev-yub
    build: ./yubico-net-sdk
    init: true
    stop_signal: SIGKILL
    labels:
      com.docker.devenvironments: "true"
      com.docker.devenvironments.compose: "true"
      com.docker.devenvironments.container: "true"
      com.docker.devenvironments.name: sdb_dev
networks:
  default:
    name: networks-sdb_dev
    attachable: true
  # portainer_agent:
  #   driver: overlay
  #   attachable: true

volumes:
  volume-bin-sol:
    name: volume-bin-sol
