#!/bin/bash
set -a


if [ -f ../sdb.env ]; then
  export $(echo $(cat sdb.env | sed 's/#.*//g'| xargs) | envsubst)
fi
if [ -f ../sol.env ]; then
  export $(echo $(cat sol.env | sed 's/#.*//g'| xargs) | envsubst)
fi
if [ -f ../yub.env ]; then
  export $(echo $(cat yub.env | sed 's/#.*//g'| xargs) | envsubst)
fi
set +a

cd ../yubico-net-sdk/Yubico.NativeShims
docker compose up -d