#!/bin/bash
set -ax
cd ..
set -a
source <(cat ../sdb.env | sed -e '/^#/d;/^\s*$/d' -e "s/'/'\\\''/g" -e "s/=\(.*\)/='\1'/g")
source <(cat ../yub.env | sed -e '/^#/d;/^\s*$/d' -e "s/'/'\\\''/g" -e "s/=\(.*\)/='\1'/g")
set +a

cd ../yubico-net-sdk/Yubico.NativeShims
docker compose up -d