#!/bin/bash
set -ax
cd ../sol
. sdb.ini
set +a

# TODO: add compose yaml
cd sdk/docker-solana

docker login -u="${DOCKER_USERNAME}" -p="${DOCKER_PASSWORD}"
docker compose build
docker compose push
docker compose up -d