#!/usr/bin/env bash
set -ex
cd ../solana
eval "$(ci/channel-info.sh)"
source ci/rust-version.sh

CHANNEL_OR_TAG=
if [[ -n "$CI_TAG" ]]; then
  SOLANA_CHANNEL_OR_TAG=$CI_TAG
else
  SOLANA_CHANNEL_OR_TAG=$CHANNEL
fi

echo "$SOLANA_CHANNEL_OR_TAG" \n

exit 0