#!/bin/bash
set -ax
cd ../solana
. sdb.ini
set +ax

cd ../solana
/bin/bash sdk/docker-solana/build.sh
docker tag ${SDB_SOL_DOCKER_IMG}:${SDB_YUB_DOCKER_TAG} ${SDB_SOL_DOCKER_IMG}:latest
docker push ${SDB_SOL_DOCKER_IMG}:${SDB_YUB_DOCKER_TAG}
