#!/bin/bash
set -ax
cd ../solana
# /bin/bash ../scripts/solana-version-get
. ci/check-channel-version.sh
. ../sdb.env CHANNEL_OR_TAG=$CHANNEL_OR_TAG SOLANA_CHANNEL_OR_TAG=$CHANNEL_OR_TAG=$CHANNEL_OR_TAG
. ../sol.env CHANNEL_OR_TAG=$CHANNEL_OR_TAG SOLANA_CHANNEL_OR_TAG=$CHANNEL_OR_TAG=$CHANNEL_OR_TAG
set +a


cd ../solana
/bin/bash sdk/docker-solana/build.sh
docker push kindtek/solana-safedb-debian:latest

docker tag ${SDB_SOL_DOCKER} ${SDB_SOL_DOCKER_IMG}:latest
docker push ${SDB_SOL_DOCKER_IMG}:latest