#!/bin/bash
set -ax
/bin/bash solana-version-get
. ../solana/ci/channel-info.sh
. ../sdb.env
. ../sol.env
set +a


cd ../solana
/bin/bash sdk/docker-solana/build.sh
docker push kindtek/solana-safedb-debian:latest

docker tag ${SDB_SOL_DOCKER} ${SDB_SOL_DOCKER_IMG}:latest
docker push ${SDB_SOL_DOCKER_IMG}:latest