#!/bin/bash

export USER_ID=1000 
export GROUP_ID=1000 
export ARTIFACT_DIR=ubuntu-x64 

cd ../
set -aex
export <(cat sdb.env | sed -e '/^#/d;/^\s*$/d' -e "s/'/'\\\''/g" -e "s/=\(.*\)/='\1'/g")
set +aex
cd yubico-net-sdk/Yubico.NativeShims
/bin/bash build-ubuntu.sh

docker build tag kindtek/yubico-safedb-ubuntu kindtek/yubico-safedb-ubuntu:latest
docker build push kindtek/yubico-safedb-ubuntu:latest
