#!/bin/bash
seat -ax
cd ../solana
. ../.ini
set +a

cd ../yubico-net-sdk/Yubico.NativeShims
/bin/bash build-${YUBICO_BUILD_ENV}.sh

docker tag ${SDB_YUB_DOCKER} ${SDB_YUB_DOCKER_IMG}:latest
docker build ${SDB_YUB_DOCKER_IMG}:latest
